### ISSUE TITLE
Don't compile bower components

### ISSUE THREAD

**Issue by qml** [6to5/6to5-brunch#4]
I'm using 6to5-brunch plugin and I want to turn it off for bower components (because it's unnecessary and takes much time).
How can I do that?

**Comment by ocombe** [comment]
That would be a good idea yes :)

**Comment by ocombe** [comment]
You just needed a little bit of motivation :P
Let's try this :)

**Comment by ocombe** [comment]
It works really well! :+1: 

And now I'm not sure what to use anymore.
The source code is much more readable with 6to5 but with the sourcemaps it doesn't really matter and it's minified in production...
I'll probably keep Traceur for this one since it uses Angular, but I might use 6to5 on non-Angular projects :)
